export const environment = {
  production: true,
  resources: {
    home: 'Home',
    hello: 'Hello',
    userDetails: 'User Details...',

    createNewAccession: 'Create New Accession',
    pendingAccessions: 'Pending Accessions',
    QaAccession: 'QA Accession',
    samples: 'Samples',
    audit: 'Audit',
    sampleStatus: 'Sample status',
    labDirectorReport: 'Lab director report',

    uploadSamplePhoto: "Upload Photo of Sample",
    uploadRequisitionForm: 'Upload Requisition Form',
    addTest: 'Add test',
    addDueDate: 'Add due date',
    tubeInfo: 'Tube Info',
    tubeExpectedCount: 'Tube expected count',
    tubeActualCount: 'Tube actual count',
    isPackageIntact: 'Is pacage intact',
    contentInfo: 'Content Info',
    submit: 'Submit',
    tubeDefect: 'Tube defect verification',
    tubeDefectNotes: 'Tube defect description',
    cancel: 'Cancel',
    createNewAccessionHeader: 'Create New Accession',
    patientsInProgress: 'Patients in progress',
    createNewAccessionButtonText: 'Create New Accession',
    noData: 'No data to show',
    uniqueIdSavedAlertStart: 'Unique ID',
    uniqueIdSavedAlertEnd: 'was saved',
    newRequisitionForm: 'New Requisition Form',
    testOrderedLabel: 'Test Ordered',
    requisitionFormFlatTab: 'Unique ID',
    requisitionFormFormatedTab: 'Requisition Form',
    requisitionFormValidationsTab: 'Validation',
    uniqeId: 'Unique ID',

    greeting: 'Wellcome to',
    userName: 'Username',
    password: 'Password',
    rememberUser: 'Remembre Username',
    signIn: 'Sign in',
    copyright: 'Copyright © 2019 Nucleix Ltd. All rights reserved',

    generalInfo: 'General Info',
    acctNumber: 'Acount number',
    phNumber: 'Phone number',
    managePictures: 'Manage Pictures',
    uploadPictures: 'Upload Sample Pictures',
    viewPictures: 'View & Manage Pictures',
    fName: 'First name',
    mName: 'Middle name initial',
    lName: 'Last name',
    dob: 'Date of birth',
    address: 'Address',
    state: 'State',
    city: 'City',
    streetAdd: 'Street & house number',
    zip: 'Zip code',
    physiciansInfo: 'Physicians Info',
    rPhysician: 'Referring phisician',
    tPhysician: 'Treating phisician',
    npi: 'NPI',
    asterisk: '*',
    requiredFields: 'Required fields',
    save: 'Save',
    printLabel: 'Print label',
    saveAndNew: 'Save & New',
    newAccessionSavedAlert: 'New accesion saved successfully, accession number = ',
    requiredFieldError: ' field is mandatory',
    incorrectPatternFieldError: 'Invalid format for ',
    middleNameLengthError: 'Please use only initials',
    genericFieldError: 'Field is invalid'
  }
};
